### ISSUE TITLE
Results visualization

### ISSUE THREAD

**Issue by SanmAIGO** [SLDGroup/MERIT#1]
I encountered some problems when learning your code. I didn't find the visual code of the results. What should I do if I want to get the visual results like those in your paper（like Figure 3: Qualitative results on Synapse multi-organ dataset.）? Can you share your code with me? Thank you very much.

**Comment by mostafij-rahman** [comment]
We have the visualization code in `utils/utils.py`. If you call the function `test_single_volume` from `utils/utils.py` with `test_save_path`, it will save the visualization results for each frame. We call this function from the `inference` function of `test_synapse.py`. We think it may help. 

We applicative your interest in our work.

Thanks,
Mostafij

**Comment by SanmAIGO** [comment]
> We have the visualization code in `utils/utils.py`. If you call the function `test_single_volume` from `utils/utils.py` with `test_save_path`, it will save the visualization results for each frame. We call this function from the `inference` function of `test_synapse.py`. We think it may help.
> 
> We applicative your interest in our work.
> 
> Thanks, Mostafij

Thank you very much! Best
